// LOGOUT
export const LOGOUT_REQUEST = 'USER/LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'USER/LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'USER/LOGOUT_FAILED';
// LOGIN
export const LOGIN_REQUEST = 'USER/LOGIN_REQUEST';
export const LOGIN_SUCCEED = 'USER/LOGIN_SUCCEED';
export const LOGIN_FAILED = 'USER/LOGIN_FAILED';
// USER
export const USER_REQUEST = 'USER/USER_REQUEST';
export const USER_SUCCESS = 'USER/USER_SUCCESS';
export const USER_FAILED = 'USER/USER_FAILED';
